Repository kookmin-sw/capstone-2025-25, pull requests merged in 2025-04, with the labels that each got.

#60 마인드맵 GPT API 연동 작업
  frontend/src/components/reactFlow/FlowWrapper.tsx
  frontend/src/components/reactFlow/nodes/ui/AnswerInputNode.tsx
  frontend/src/components/reactFlow/nodes/ui/DragIcon.tsx
  frontend/src/components/reactFlow/nodes/ui/QuestionListNode.tsx
  frontend/src/components/reactFlow/nodes/ui/RootNode.tsx
  frontend/src/components/reactFlow/nodes/ui/SummaryNode.tsx
  frontend/src/components/ui/Dialog.tsx
  frontend/src/components/ui/skeleton.tsx
  frontend/src/hooks/queries/mindmap/useConvertScheduleToTodo.ts
  frontend/src/hooks/queries/mindmap/useConvertThoughtToList.ts
  frontend/src/hooks/queries/mindmap/useGenerateSchedule.ts
  frontend/src/hooks/queries/mindmap/useGenerateThought.ts
  frontend/src/hooks/queries/mindmap/useSummarizeNode.ts
  frontend/src/hooks/queries/useMindmap.ts
  frontend/src/lib/mindMap.ts
  frontend/src/store/mindMapStore.ts
  frontend/src/types/api/mindmap/request.ts
  frontend/src/types/mindMap.ts
Labels: ✨ Feature, 📬 API, 🌈 FE

#67 refactor: 마인드맵 예외 처리 시 ID 파라미터 제거
  backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
Labels: 🐞 BugFix, 🔥 BE

#71 색상 변수 수정
  frontend/src/styles/index.css
Labels: ⚙ Chore, 🌈 FE

#69 fix: RedisTemplate를 활용한 코드 구조에서 Spring Data Redis를 활용한 코드로 수정
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/domain/auth/exception/InvalidRefreshTokenException.java
  backend/src/main/java/capstone/backend/domain/auth/exception/RefreshTokenExpiredException.java
  backend/src/main/java/capstone/backend/domain/auth/repository/RefreshTokenRedisRepository.java
  backend/src/main/java/capstone/backend/domain/auth/schema/RefreshToken.java
  backend/src/main/java/capstone/backend/domain/auth/service/AuthService.java
  backend/src/main/java/capstone/backend/global/property/RedisProperty.java
  backend/src/main/java/capstone/backend/global/redis/RedisConfig.java
  backend/src/main/java/capstone/backend/global/redis/RedisService.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtProvider.java
  backend/src/main/java/capstone/backend/global/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 📬 API, 🔨 Refactor, 🔥 BE

#82 Fix: 뽀모도로 도메인 수정 및 API 로직 수정
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/DailyPomodoroSummaryController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/PomodoroController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/request/CreatePomodoroRequest.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/request/LinkedPomodoroRequest.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/request/MonthlyParamsDTO.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/SidebarPomodoroResponse.java
  backend/src/main/java/capstone/backend/domain/pomodoro/repository/PomodoroRepository.java
  backend/src/main/java/capstone/backend/domain/pomodoro/schema/Pomodoro.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
Labels: 📬 API, 🚨 HotFix, 🔥 BE

#73 뽀모도로 / 뽀모도로 총량 데이터 도메인 개발
  backend/src/main/java/capstone/backend/BackendApplication.java
  backend/src/main/java/capstone/backend/domain/member/scheme/Member.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/DailyPomodoroSummaryController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/PomodoroController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/request/CreatePomodoroRequest.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/request/MonthlyParamsDTO.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/request/RecordPomodoroRequest.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/DailyPomodoroDTO.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/SidebarPomodoroResponse.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/SidebarResponse.java
  backend/src/main/java/capstone/backend/domain/pomodoro/exception/PomodoroDurationException.java
  backend/src/main/java/capstone/backend/domain/pomodoro/exception/PomodoroNotFoundException.java
  backend/src/main/java/capstone/backend/domain/pomodoro/repository/DailyPomodoroSummaryRepository.java
  backend/src/main/java/capstone/backend/domain/pomodoro/repository/PomodoroRepository.java
  backend/src/main/java/capstone/backend/domain/pomodoro/schema/DailyPomodoroSummary.java
  backend/src/main/java/capstone/backend/domain/pomodoro/schema/Pomodoro.java
  backend/src/main/java/capstone/backend/domain/pomodoro/schema/PomodoroCycle.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/DailyPomodoroSummaryService.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
  backend/src/main/java/capstone/backend/domain/pomodoro/util/PomodoroTimeUtils.java
  backend/src/main/java/capstone/backend/global/api/exception/ApiExceptionHandler.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#102 [FE] feat: 로그인 퍼블리싱 및 기능 구현
  frontend/.gitignore
  frontend/src/api/client.ts
  frontend/src/api/endpoints.ts
  frontend/src/constants/auth.ts
  frontend/src/pages/callback.tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/register.tsx
  frontend/src/routes.ts
  frontend/src/services/loginService.ts
  frontend/src/store/authStore.ts
Labels: ✨ Feature, 🌈 FE

#105 [BE] feat: 상단바에 들어갈 유저 데이터 조회 API 작성
  backend/src/main/java/capstone/backend/domain/member/controller/MemberController.java
  backend/src/main/java/capstone/backend/domain/member/dto/response/UserDataDTO.java
  backend/src/main/java/capstone/backend/domain/member/service/MemberService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#101 [FE] feat: 뽀모도로 퍼블리싱 및 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/Modal.tsx
  frontend/src/components/ui/Accordion.tsx
  frontend/src/components/ui/Modal/AddPomodoro.tsx
  frontend/src/components/ui/Modal/DeletePomodoro.tsx
  frontend/src/components/ui/Modal/EndPomodoro.tsx
  frontend/src/components/ui/MultiSlider.tsx
  frontend/src/components/ui/SubSidebarAccordion.tsx
  frontend/src/components/ui/pomodoro/PomodoroItem.tsx
  frontend/src/components/ui/pomodoro/PomodoroResult.tsx
  frontend/src/components/ui/pomodoro/PomodoroTimer.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/components/ui/sidebar/panel/PomodoroPanel.tsx
  frontend/src/components/ui/sidebar/panel/PomodoroSubSidebar.tsx
  frontend/src/pages/pomodoro.tsx
  frontend/src/routes.ts
  frontend/src/types/api/pomodoro/index.ts
  frontend/src/types/api/pomodoro/request.ts
  frontend/src/types/api/pomodoro/response.ts
  frontend/src/types/pomodoro.ts
Labels: ✨ Feature, 🌈 FE

#88 [FE] feat: 마인드맵 Pane 클릭 시, 노드 상태 복원 기능 구현
  frontend/src/components/reactFlow/FlowWrapper.tsx
  frontend/src/components/reactFlow/nodes/ui/QuestionListNode.tsx
  frontend/src/store/mindMapStore.ts
Labels: ✨ Feature, 🌈 FE

#107 [FE] test: 마인드맵 더미데이터로 실행 흐름 처리
  frontend/src/assets/sidebar/check-list.svg
  frontend/src/assets/sidebar/dashboard.svg
  frontend/src/assets/sidebar/mindmap.svg
  frontend/src/components/ui/Modal/AddPomodoro.tsx
  frontend/src/components/ui/Modal/DeletePomodoro.tsx
  frontend/src/components/ui/pomodoro/PomodoroItem.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/components/ui/sidebar/panel/MindmapPanel.tsx
  frontend/src/components/ui/sidebar/panel/PomodoroPanel.tsx
  frontend/src/components/ui/sidebar/panel/SidebarPanel.tsx
  frontend/src/components/ui/sidebar/panel/mindmap/MindmapCard.tsx
  frontend/src/components/ui/sidebar/subSidebar/CommonSubSidebarWrapper.tsx
  frontend/src/components/ui/sidebar/subSidebar/SubSidebar.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapAddButton.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapSubSidebar.tsx
  frontend/src/components/ui/sidebar/subSidebar/pomodoro/PomodoroSubSidebar.tsx
  frontend/src/lib/formatDate.ts
  frontend/src/mock/mindmap.ts
  frontend/src/mock/pomorodo.ts
  frontend/src/pages/mindmap.tsx
  frontend/src/pages/mindmapDetail.tsx
  frontend/src/pages/pomodoro.tsx
  frontend/src/routes.ts
  frontend/src/services/.gitkeep
  frontend/src/store/mindmapListStore.ts
  frontend/src/store/pomodoro.ts
  frontend/src/types/mindMap.ts
Labels: ✅ Test, 🌈 FE

#99 [FE] feat: 아이젠하워 매트릭스 퍼블리싱
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/data.ts
  frontend/src/components/eisenhower/CreateTaskForm.tsx
  frontend/src/components/eisenhower/Droppable.tsx
  frontend/src/components/eisenhower/FilterBar.tsx
  frontend/src/components/eisenhower/TaskDetailSidebar.tsx
  frontend/src/components/eisenhower/card/DragOverlayCard.tsx
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/eisenhower/data/tasks.ts
  frontend/src/components/eisenhower/filter/CategoryBadge.tsx
  frontend/src/components/eisenhower/filter/DateRangePicker.tsx
  frontend/src/components/eisenhower/filter/SingleDatePicker.tsx
  frontend/src/components/eisenhower/filter/TypeBadge.tsx
  frontend/src/components/eisenhower/view/CompletedView.tsx
  frontend/src/components/eisenhower/view/PriorityView.tsx
  frontend/src/components/ui/Badge.tsx
  frontend/src/components/ui/Label.tsx
  frontend/src/components/ui/Sheet.tsx
  frontend/src/components/ui/Tabs.tsx
  frontend/src/components/ui/calendar.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/components/ui/sonner.tsx
  frontend/src/constants/category.ts
  frontend/src/constants/eisenhower.ts
  frontend/src/constants/section.ts
  frontend/src/context/TaskModalProvider.tsx
  frontend/src/hooks/useOutsideClick.ts
  frontend/src/hooks/useTaskDnD.ts
  frontend/src/hooks/useTaskFilters.ts
  frontend/src/pages/matrix.tsx
  frontend/src/store/useCategoryStore.ts
  frontend/src/types/category.ts
  frontend/src/types/task.ts
  frontend/src/utils/category.ts
Labels: ✨ Feature, 🌈 FE

#106 [BE] feat: 아이젠하워 검색, 알림 기능 구현
  backend/src/main/java/capstone/backend/BackendApplication.java
  backend/src/main/java/capstone/backend/domain/eisenhower/batch/NotificationJobConfig.java
  backend/src/main/java/capstone/backend/domain/eisenhower/batch/step/DeleteOldNotificationsTasklet.java
  backend/src/main/java/capstone/backend/domain/eisenhower/batch/step/GenerateNotificationTasklet.java
  backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerItemController.java
  backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerNotificationController.java
  backend/src/main/java/capstone/backend/domain/eisenhower/dto/response/EisenhowerNotificationResponse.java
  backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerNotification.java
  backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepository.java
  backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerNotificationRepository.java
  backend/src/main/java/capstone/backend/domain/eisenhower/scheduler/EisenhowerNotificationScheduler.java
  backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerItemService.java
  backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerNotificationService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#119 [BE] feat: 뽀모도로 총 계획 시간, 계획 총 집중/휴식 시간 추가
  backend/src/main/java/capstone/backend/domain/pomodoro/schema/Pomodoro.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#126 Qa/89 mindmap
  frontend/.gitignore
  frontend/src/assets/q1.svg
  frontend/src/assets/q2.svg
  frontend/src/assets/q3.svg
  frontend/src/assets/q4.svg
  frontend/src/components/eisenhower/TaskDetailSidebar.tsx
  frontend/src/components/reactFlow/nodes/ui/QuestionListNode.tsx
  frontend/src/components/reactFlow/ui/NodeSelectionPanel.tsx
  frontend/src/components/ui/Modal/AddPomodoro.tsx
  frontend/src/components/ui/Modal/DeletePomodoro.tsx
  frontend/src/components/ui/Modal/NodeTaskModal.tsx
  frontend/src/components/ui/Tabs.tsx
  frontend/src/components/ui/pomodoro/PomodoroItem.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
  frontend/src/constants/auth.ts
  frontend/src/pages/matrix.tsx
  frontend/src/pages/mindmap.tsx
  frontend/src/store/matrixStore.ts
  frontend/src/store/mindmapListStore.ts
  frontend/src/store/nodeSelection.ts
  frontend/src/store/pomodoro.ts
  frontend/src/types/mindMap.ts
  frontend/src/types/task.ts
Labels: 🐞 BugFix, 🔨 Refactor, 🌈 FE

#128 서브사이드바 관련 & 추가 수정사항 반영
  frontend/index.html
  frontend/src/assets/.gitkeep
  frontend/src/components/ui/MultiSlider.tsx
  frontend/src/components/ui/SubSidebarAccordion.tsx
  frontend/src/components/ui/pomodoro/PomodoroItem.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/components/ui/sidebar/subSidebar/SubSidebar.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/matrix.tsx
  frontend/src/pages/register.tsx
  frontend/src/store/sidebarStore.ts
Labels: 🔨 Refactor, 🚨 HotFix, 🌈 FE

#122 [BE] chore: cloudwatch 로그 수집 코드 작성
  .github/workflows/backend-ci-cd.yml
  backend/build.gradle
  backend/logback.xml
  backend/src/main/java/capstone/backend/global/property/AwsProperty.java
  backend/src/main/resources/application.yml
Labels: ⚙ Chore, 🌏 Deploy, 🔥 BE

#134 [FE] refactor: 전체 프로젝트 타입 정의 표준화 및 오류 수정
  frontend/package.json
  frontend/src/components/eisenhower/AddTask.tsx
  frontend/src/components/eisenhower/TaskDetailSidebar.tsx
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/eisenhower/filter/CategoryBadge.tsx
  frontend/src/components/eisenhower/filter/TypeBadge.tsx
  frontend/src/components/eisenhower/view/CompletedView.tsx
  frontend/src/components/eisenhower/view/PriorityView.tsx
  frontend/src/components/reactFlow/FlowWrapper.tsx
  frontend/src/components/reactFlow/ui/NodeSelectionPanel.tsx
  frontend/src/components/ui/Modal/DeletePomodoro.tsx
  frontend/src/components/ui/Modal/NodeTaskModal.tsx
  frontend/src/components/ui/MultiSlider.tsx
  frontend/src/components/ui/pomodoro/PomodoroResult.tsx
  frontend/src/components/ui/pomodoro/PomodoroTimer.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapAddButton.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapCard.tsx
  frontend/src/components/ui/sidebar/subSidebar/mindmap/MindmapSubSidebar.tsx
  frontend/src/constants/section.ts
  frontend/src/hooks/queries/mindmap/useConvertThoughtToList.ts
  frontend/src/hooks/queries/mindmap/useGenerateThought.ts
  frontend/src/hooks/useTaskDnD.ts
  frontend/src/hooks/useTaskFilters.ts
  frontend/src/lib/generateNumericId.ts
  frontend/src/lib/parseIdParam.ts
  frontend/src/mock/mindmap.ts
  frontend/src/mock/task.ts
  frontend/src/pages/mindmap.tsx
  frontend/src/pages/pomodoro.tsx
  frontend/src/store/matrixStore.ts
  frontend/src/store/mindMapStore.ts
  frontend/src/store/mindmapListStore.ts
  frontend/src/store/pomodoro.ts
  frontend/src/types/api/pomodoro/index.ts
  frontend/src/types/api/pomodoro/response.ts
  frontend/src/types/commonTypes.ts
  frontend/src/types/mindMap.ts
  frontend/src/types/pomodoro.ts
  frontend/src/types/task.ts
Labels: 🔨 Refactor, 🌈 FE

#140 fix: CORS 에러 해결
  backend/src/main/java/capstone/backend/global/property/CorsProperty.java
  backend/src/main/java/capstone/backend/global/security/SecurityConfig.java
Labels: ⚙ Chore, 🐞 BugFix, 📬 API, 🔥 BE

#142 [BE] Fix: MindMap 조회 오류 및 응답 DTO 구조 개선
  backend/logback-spring.xml
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapResponse.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/SidebarMindMapResponse.java
Labels: 🐞 BugFix, 🔥 BE

#143 fix: logback-spring.xml 코드 수정 및 로깅 테스트
  backend/logback-spring.xml
Labels: 🐞 BugFix

#146 [BE] refact: measured 필드 null 방지
  backend/src/main/java/capstone/backend/domain/mindmap/entity/Measured.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/Node.java
  backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
Labels: 🔨 Refactor, 🔥 BE

#144 [BE] chore: Docker Logs를 Cloudwatch에 연동
  .github/workflows/backend-ci-cd.yml
  backend/build.gradle
  backend/docker-compose.yml
  backend/logback-spring.xml
Labels: ⚙ Chore, 🌏 Deploy, 🔥 BE

#153 refact: NodeResponse에 NodeData 포함하도록 구조 변경
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapResponse.java
Labels: 🐞 BugFix, 🔥 BE

#150 [BE] feat: GPT API 구조 리팩터링 및 아이젠하워 작업 우선순위 추천 API 구현
  gpt/main.py
  gpt/models/request.py
  gpt/models/response.py
  gpt/prompts/__init__.py
  gpt/prompts/convert_task_prompt.txt
  gpt/prompts/eisenhower_order_prompt.txt
  gpt/prompts/summarize_prompt.txt
  gpt/prompts/thinking_prompt.txt
  gpt/prompts/todo_prompt.txt
  gpt/requirements.txt
  gpt/routes/gpt.py
  gpt/routes/gpt_router.py
  gpt/services/__init__.py
  gpt/services/gpt_service.py
  gpt/utils/exception_handler.py
  gpt/utils/gpt_helper.py
  gpt/utils/logging.py
  gpt/utils/mindmap.py
  gpt/utils/prompt_loader.py
Labels: ⚙ Chore, ✨ Feature, 📬 API, 🔨 Refactor, 🔥 BE

#156 hotfix: PUT Cors 요청 허용
  backend/src/main/java/capstone/backend/global/security/SecurityConfig.java
Labels: ⚙ Chore, 🐞 BugFix, 🔥 BE

#154 [BE] refactor: GPT API 예외 처리 및 문서화 작업
  gpt/main.py
  gpt/models/request.py
  gpt/models/response.py
  gpt/routes/gpt_router.py
Labels: ⚙ Chore, 🔨 Refactor, 🔥 BE

#160 feat: 뽀모도로 생성 시 ID 값 반환 로직 추가
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/PomodoroController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/PomodoroDTO.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#163 [BE] fix: swagger config 설정 변경 및 컨트롤러 네이밍 설정
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/domain/member/controller/MemberController.java
  backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/DailyPomodoroSummaryController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/PomodoroController.java
  backend/src/main/java/capstone/backend/global/swagger/SwaggerConfig.java
Labels: ⚙ Chore, 📃 Docs, 🔥 BE

#162 feat: 마인드맵 수정 요청 시 Req body 변경 및 카테고리 조회
  backend/src/main/java/capstone/backend/domain/eisenhower/exception/MindMapNotLinkedToEisenhowerException.java
  backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepository.java
  backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerItemService.java
  backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/request/MindMapRequest.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/request/UpdateMindMapRequest.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/MindMap.java
  backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
Labels: 📬 API, 🔥 BE

#167 [BE] fix: HTTPS 적용으로 인한 cookie 설정 변경
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtAuthenticationFilter.java
Labels: ⚙ Chore, 🌏 Deploy, 🔥 BE

#168 [FE] feat: 로그인 페이지 퍼블리싱 및 토큰 로직 수정
  frontend/src/api/client.ts
  frontend/src/assets/hero-section.png
  frontend/src/assets/kakao.svg
  frontend/src/assets/naver.svg
  frontend/src/components/eisenhower/view/PriorityView.tsx
  frontend/src/components/ui/Modal/AddPomodoro.tsx
  frontend/src/hooks/useAuthRedirect.ts
  frontend/src/hooks/useExchangeCodeForToken.ts
  frontend/src/layouts/AuthLayout.tsx
  frontend/src/pages/callback.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/matrix.tsx
  frontend/src/services/authService.ts
  frontend/src/services/loginService.ts
  frontend/src/utils/cookie.ts
Labels: ✨ Feature, 🌈 FE
