Repository kookmin-sw/capstone-2025-25, pull requests merged in 2025-05, with the labels that each got.

#174 [BE]: feat: 브레인스토밍 마인드맵 관련 새 기능 임시 코드 작성(GPT)
  gpt/main.py
  gpt/models/request.py
  gpt/models/temporary_request.py
  gpt/models/temporary_response.py
  gpt/prompts/chunk_analysis_prompt.txt
  gpt/prompts/extract_chucks_prompt.txt
  gpt/prompts/mindmap_to_chunk_prompt.txt
  gpt/routes/temporary_router.py
Labels: ✨ Feature, 📬 API, 🔥 BE

#171 [BE] fix: 사용하지 않는 controller v1으로 분기 & 기획 수정 이후 사용하는 controller를 v2로 분기
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/v1/PomodoroV1Controller.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/DailyPomodoroSummaryController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/PomodoroV2Controller.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
Labels: 🔨 Refactor, 🔥 BE

#186 index.html 추가
  index.html
Labels: 📃 Docs

#181 refact: 사용하지 않는 마인드맵 API V1으로 분기 처리
  backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
Labels: 🔨 Refactor, 🔥 BE

#183 [BE] refactor: GPT API 기능 변경에 따른 코드 리펙터링
  gpt/main.py
  gpt/models/brainstorming_request.py
  gpt/models/brainstorming_response.py
  gpt/models/eisenhower_request.py
  gpt/models/eisenhower_response.py
  gpt/models/mindmap_request.py
  gpt/models/mindmap_response.py
  gpt/prompts/brainstorming/chunk_analysis_prompt.txt
  gpt/prompts/brainstorming/extract_chucks_prompt.txt
  gpt/prompts/brainstorming/mindmap_to_chunk_prompt.txt
  gpt/prompts/chunk_analysis_prompt.txt
  gpt/prompts/eisenhower/eisenhower_order_prompt.txt
  gpt/prompts/extract_chucks_prompt.txt
  gpt/prompts/mindmap/convert_task_prompt.txt
  gpt/prompts/mindmap/summarize_prompt.txt
  gpt/prompts/mindmap/thinking_prompt.txt
  gpt/prompts/mindmap/todo_prompt.txt
  gpt/prompts/mindmap_to_chunk_prompt.txt
  gpt/routes/brainstorming_router.py
  gpt/routes/eisenhower_router.py
  gpt/routes/gpt_router.py
  gpt/routes/mindmap_router.py
  gpt/routes/temporary_router.py
  gpt/utils/brainstorming.py
  gpt/utils/gpt_helper.py
Labels: 📬 API, 🔨 Refactor, 🔥 BE

#184 [BE] feat: Bubble 도메인 관련 API 설계
  backend/build.gradle
  backend/src/main/java/capstone/backend/domain/bubble/controller/v2/BubbleController.java
  backend/src/main/java/capstone/backend/domain/bubble/dto/request/ConfirmBubbleRequest.java
  backend/src/main/java/capstone/backend/domain/bubble/dto/request/PromptRequest.java
  backend/src/main/java/capstone/backend/domain/bubble/dto/response/BubbleDTO.java
  backend/src/main/java/capstone/backend/domain/bubble/dto/response/PromptResponse.java
  backend/src/main/java/capstone/backend/domain/bubble/entity/Bubble.java
  backend/src/main/java/capstone/backend/domain/bubble/exception/BubbleNotFoundException.java
  backend/src/main/java/capstone/backend/domain/bubble/repository/BubbleRepository.java
  backend/src/main/java/capstone/backend/domain/bubble/service/BubbleService.java
  backend/src/main/java/capstone/backend/domain/bubble/service/WebFluxService.java
  backend/src/main/java/capstone/backend/domain/member/service/MemberService.java
  backend/src/main/java/capstone/backend/global/api/webflux/WebFluxConfig.java
  backend/src/main/java/capstone/backend/global/database/querydsl/QuerydslConfig.java
  backend/src/main/java/capstone/backend/global/database/redis/RedisConfig.java
  backend/src/main/java/capstone/backend/global/security/SecurityConfig.java
Labels: ⚙ Chore, ✨ Feature, 📬 API, 🔥 BE

#197 [BE] refactor: 아이젠하워 관련 기능 수정 사항 반영
  backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerCategoryController.java
  backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerItemController.java
  backend/src/main/java/capstone/backend/domain/eisenhower/controller/EisenhowerNotificationController.java
  backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemCreateRequest.java
  backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemFilterRequest.java
  backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemUpdateRequest.java
  backend/src/main/java/capstone/backend/domain/eisenhower/dto/response/EisenhowerItemResponse.java
  backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
  backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepository.java
  backend/src/main/java/capstone/backend/domain/eisenhower/repository/EisenhowerItemRepositoryImpl.java
  backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerItemService.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/SidebarMindMapResponse.java
  backend/src/main/java/capstone/backend/domain/mindmap/repository/MindMapRepository.java
  backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/DailyPomodoroSummaryController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/PomodoroV2Controller.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/SidebarPomodoroResponse.java
  backend/src/main/java/capstone/backend/domain/pomodoro/repository/PomodoroRepository.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
  backend/src/main/java/capstone/backend/global/swagger/SwaggerConfig.java
Labels: 📬 API, 🔨 Refactor, 🔥 BE

#192 [BE] feat: 오늘의 할 일 도메인 관련 API 로직 구현
  backend/src/main/java/capstone/backend/domain/todayTask/controller/TodayTaskItemController.java
  backend/src/main/java/capstone/backend/domain/todayTask/dto/request/TodayTaskItemCreateRequest.java
  backend/src/main/java/capstone/backend/domain/todayTask/dto/response/TodayTaskItemResponse.java
  backend/src/main/java/capstone/backend/domain/todayTask/entity/TodayTaskItem.java
  backend/src/main/java/capstone/backend/domain/todayTask/exception/TodayTaskNotFoundException.java
  backend/src/main/java/capstone/backend/domain/todayTask/repository/TodayTaskItemRepository.java
  backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskItemService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#201 [FE]: 변경된 기획안에 맞는 헤더 & 사이드바 컴포넌트 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/sidebar/bw-brainstorming.svg
  frontend/src/assets/sidebar/bw-eisenhower.svg
  frontend/src/assets/sidebar/bw-store.svg
  frontend/src/assets/sidebar/bw-today-todo.svg
  frontend/src/assets/sidebar/color-brainstorming.svg
  frontend/src/assets/sidebar/color-eisenhower.svg
  frontend/src/assets/sidebar/color-store.svg
  frontend/src/assets/sidebar/color-today-todo.svg
  frontend/src/assets/tmp-logo.svg
  frontend/src/components/ui/header/Header.tsx
  frontend/src/components/ui/sidebar/BottomBar.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/layouts/DefaultLayout.tsx
  frontend/vite.config.ts
Labels: ✨ Feature, 🎨 Html&css, 🌈 FE

#194 [FE]: 오늘의 할 일 페이지 퍼블리싱
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/chart.tsx
  frontend/src/components/ui/chart/DailyCompletionChart.tsx
  frontend/src/components/ui/chart/TodayCompleteChart.tsx
  frontend/src/pages/today.tsx
  frontend/src/styles/shadcn-global.css
Labels: ✨ Feature, 🎨 Html&css, 🌈 FE

#206 [BE] fix: 프론트 요청 사항 반영하여 코드 수정 작업
  backend/src/main/java/capstone/backend/domain/bubble/controller/v2/BubbleController.java
  backend/src/main/java/capstone/backend/domain/bubble/dto/request/BubbleUpdateRequest.java
  backend/src/main/java/capstone/backend/domain/bubble/entity/Bubble.java
  backend/src/main/java/capstone/backend/domain/bubble/service/BubbleService.java
  backend/src/main/java/capstone/backend/domain/eisenhower/dto/request/EisenhowerItemCreateRequest.java
  backend/src/main/java/capstone/backend/domain/eisenhower/dto/response/EisenhowerItemResponse.java
  backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
  backend/src/main/java/capstone/backend/domain/eisenhower/scheduler/EisenhowerNotificationScheduler.java
  backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskItemService.java
Labels: 🐞 BugFix, 📬 API, 🚨 HotFix, 🔥 BE

#208 [BE] fix: 아이젠하워 작업 category 연관관계 오류 수정
  backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
Labels: 🐞 BugFix, 📬 API, 🔥 BE

#209 오늘의 할 일 API 연동
  frontend/src/api/endpoints.ts
  frontend/src/components/today/TodayList.tsx
  frontend/src/components/today/TodayMainDashborad.tsx
  frontend/src/components/ui/chart/DailyCompletionChart.tsx
  frontend/src/components/ui/chart/TodayCompleteChart.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/hooks/queries/category/useGetCategoryList.ts
  frontend/src/hooks/queries/today/useGetTodayTodoCompletedCount.ts
  frontend/src/hooks/queries/today/useGetTodayTodoCount.ts
  frontend/src/hooks/queries/today/useGetTodayTodoList.ts
  frontend/src/hooks/queries/today/useGetYesterdayTodoList.ts
  frontend/src/hooks/queries/today/useMoveToday.ts
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/pages/home.tsx
  frontend/src/pages/today.tsx
  frontend/src/services/categoryService.ts
  frontend/src/services/todayService.ts
  frontend/src/types/api/category/index.ts
  frontend/src/types/api/category/request.ts
  frontend/src/types/api/category/response.ts
  frontend/src/types/api/today/index.ts
  frontend/src/types/api/today/request.ts
  frontend/src/types/api/today/response.ts
  frontend/src/types/category.ts
  frontend/src/types/todayTodo.ts
Labels: ✨ Feature, 📬 API, 🌈 FE

#215 마인드맵 - 브레인스토밍 연결
  frontend/src/api/endpoints.ts
  frontend/src/components/mindmap/MindmapSkeleton.tsx
  frontend/src/components/mindmap/MindmapWrapper.tsx
  frontend/src/hooks/queries/brainstorming/usePatchBubble.ts
  frontend/src/hooks/queries/gpt/useBrainStormingAnalyze.ts
  frontend/src/hooks/queries/gpt/useBrainStormingRewrite.ts
  frontend/src/pages/brainstorming.tsx
  frontend/src/pages/mindmap.tsx
  frontend/src/routes.ts
  frontend/src/services/brainstormingService.ts
  frontend/src/services/gptService.ts
  frontend/src/store/mindMapStore.ts
  frontend/src/types/api/gpt/index.ts
  frontend/src/types/api/gpt/request.ts
  frontend/src/types/api/gpt/response.ts
Labels: ✨ Feature, 📬 API, 🌈 FE

#214 [FE] 아이젠하워 API 연동
  frontend/package-lock.json
  frontend/src/api/endpoints.ts
  frontend/src/components/eisenhower/FilterBar.tsx
  frontend/src/components/eisenhower/TaskDetailSidebar.tsx
  frontend/src/components/eisenhower/TaskModal.tsx
  frontend/src/components/eisenhower/card/DragOverlayCard.tsx
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/eisenhower/filter/CategoryBadge.tsx
  frontend/src/components/eisenhower/view/CompletedView.tsx
  frontend/src/components/eisenhower/view/PriorityView.tsx
  frontend/src/pages/matrix.tsx
  frontend/src/services/eisenhowerCategoryService.ts
  frontend/src/services/eisenhowerService.ts
  frontend/src/store/matrixStore.ts
  frontend/src/store/useCategoryStore.ts
  frontend/src/types/api/eisenhower/index.ts
  frontend/src/types/api/eisenhower/response.ts
  frontend/src/types/task.ts
Labels: 📬 API, 🌈 FE

#218 [FE]: 오늘의 할 일 페이지 반응형 수정
  frontend/src/components/today/TodayMainDashborad.tsx
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/pages/today.tsx
Labels: ✨ Feature, 🌈 FE

#200 [BE] 보관함 API 구현
  backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryFolderController.java
  backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryItemController.java
  backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryFolder.java
  backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryItem.java
  backend/src/main/java/capstone/backend/domain/inventory/exception/FolderDeletionNotAllowedException.java
  backend/src/main/java/capstone/backend/domain/inventory/exception/FolderNotFoundException.java
  backend/src/main/java/capstone/backend/domain/inventory/exception/InventoryItemNotFoundException.java
  backend/src/main/java/capstone/backend/domain/inventory/repository/InventoryFolderRepository.java
  backend/src/main/java/capstone/backend/domain/inventory/repository/InventoryItemRepository.java
  backend/src/main/java/capstone/backend/domain/inventory/request/InventoryFolderRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/request/InventoryItemCreateRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/request/InventoryItemMoveRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/request/InventoryItemUpdateRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/response/InventoryFolderResponse.java
  backend/src/main/java/capstone/backend/domain/inventory/response/InventoryItemResponse.java
  backend/src/main/java/capstone/backend/domain/inventory/service/InventoryFolderService.java
  backend/src/main/java/capstone/backend/domain/inventory/service/InventoryItemService.java
  backend/src/main/java/capstone/backend/domain/member/service/MemberService.java
  backend/src/main/java/capstone/backend/global/security/oauth2/service/CustomOAuth2UserService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#221 [BE] feat: 오늘의 할 일 및 분석 구현
  backend/src/main/java/capstone/backend/domain/eisenhower/batch/NotificationJobConfig.java
  backend/src/main/java/capstone/backend/domain/eisenhower/entity/EisenhowerItem.java
  backend/src/main/java/capstone/backend/domain/todayTask/batch/SaveTodayTaskAnalysisTasklet.java
  backend/src/main/java/capstone/backend/domain/todayTask/batch/TodayTaskAnalysisJobConfig.java
  backend/src/main/java/capstone/backend/domain/todayTask/controller/TodayTaskAnalysisController.java
  backend/src/main/java/capstone/backend/domain/todayTask/controller/TodayTaskItemController.java
  backend/src/main/java/capstone/backend/domain/todayTask/dto/request/TodayTaskItemCreateRequest.java
  backend/src/main/java/capstone/backend/domain/todayTask/dto/request/TodayTaskUpdateRequest.java
  backend/src/main/java/capstone/backend/domain/todayTask/dto/response/TodayTaskAnalysisResponse.java
  backend/src/main/java/capstone/backend/domain/todayTask/entity/DayOfWeekEnum.java
  backend/src/main/java/capstone/backend/domain/todayTask/entity/TodayTaskAnalysis.java
  backend/src/main/java/capstone/backend/domain/todayTask/entity/TodayTaskItem.java
  backend/src/main/java/capstone/backend/domain/todayTask/exception/DuplicateTaskException.java
  backend/src/main/java/capstone/backend/domain/todayTask/repository/TodayTaskAnalysisRepository.java
  backend/src/main/java/capstone/backend/domain/todayTask/repository/TodayTaskItemRepository.java
  backend/src/main/java/capstone/backend/domain/todayTask/scheduler/TodayTaskAnalysisScheduler.java
  backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskAnalysisService.java
  backend/src/main/java/capstone/backend/domain/todayTask/service/TodayTaskItemService.java
  backend/src/main/java/capstone/backend/global/batch/runner/MultiJobLauncher.java
  backend/src/main/java/capstone/backend/global/batch/service/MultiJobExecutionService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#227 [BE] feat: 폴더 상세 조회 API 구현
  backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryFolderController.java
  backend/src/main/java/capstone/backend/domain/inventory/service/InventoryFolderService.java
Labels: 📬 API, 🔥 BE

#229 PWA 관련 설정
  frontend/package-lock.json
  frontend/package.json
  frontend/public/apple-touch-icon-180x180.png
  frontend/public/favicon.ico
  frontend/public/logo.svg
  frontend/public/manifest.json
  frontend/public/maskable-icon-512x512.png
  frontend/public/pwa-192x192.png
  frontend/public/pwa-512x512.png
  frontend/public/pwa-64x64.png
  frontend/src/assets/logo.svg
  frontend/src/root.tsx
  frontend/vite.config.ts
Labels: ⚙ Chore, ✨ Feature, 🌈 FE

#228 로그아웃 관련 로직 수정
  frontend/src/components/ui/header/Header.tsx
  frontend/src/layouts/DefaultLayout.tsx
Labels: 🐞 BugFix, 🚨 HotFix, 🌈 FE

#236 보관함 퍼블리싱 & API 연동
  frontend/src/api/endpoints.ts
  frontend/src/assets/folder.png
  frontend/src/assets/folder.svg
  frontend/src/components/inventory/InventoryItemCard.tsx
  frontend/src/components/inventory/modal/CreateFolderMoal.tsx
  frontend/src/components/inventory/modal/DeleteFolderMoal.tsx
  frontend/src/components/inventory/modal/MoveToFolderModal.tsx
  frontend/src/components/ui/Dialog.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/hooks/queries/inventory/folder/useCreateInventoryFolder.ts
  frontend/src/hooks/queries/inventory/folder/useDeleteInventoryFolder.ts
  frontend/src/hooks/queries/inventory/folder/useGetInventoryFolderDetail.ts
  frontend/src/hooks/queries/inventory/folder/useGetInventoryFolderList.ts
  frontend/src/hooks/queries/inventory/item/useDeleteInventoryItem.ts
  frontend/src/hooks/queries/inventory/item/useGetInventoryItemList.ts
  frontend/src/hooks/queries/inventory/item/useMoveInventoryItem.ts
  frontend/src/hooks/queries/inventory/item/useUpdateInventoryItem.ts
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/lib/parseIdParam.ts
  frontend/src/pages/inventory.tsx
  frontend/src/pages/inventoryDetail.tsx
  frontend/src/routes.ts
  frontend/src/services/inventoryFolderService.ts
  frontend/src/services/inventoryItemService.ts
  frontend/src/types/api/inventory/folder/index.ts
  frontend/src/types/api/inventory/folder/request.ts
  frontend/src/types/api/inventory/folder/response.ts
  frontend/src/types/api/inventory/item/index.ts
  frontend/src/types/api/inventory/item/request.ts
  frontend/src/types/api/inventory/item/response.ts
  frontend/src/types/inventory.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🌈 FE

#231 [BE] feat: 로그아웃 로직 구현
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/domain/auth/dto/request/AccessTokenRequest.java
  backend/src/main/java/capstone/backend/domain/auth/exception/AccessLogoutTokenException.java
  backend/src/main/java/capstone/backend/domain/auth/exception/InvalidTokenException.java
  backend/src/main/java/capstone/backend/domain/auth/exception/RefreshTokenNotFoundException.java
  backend/src/main/java/capstone/backend/domain/auth/exception/TokenNotFoundException.java
  backend/src/main/java/capstone/backend/domain/auth/repository/BlacklistTokenRedisRepository.java
  backend/src/main/java/capstone/backend/domain/auth/schema/BlacklistToken.java
  backend/src/main/java/capstone/backend/domain/auth/service/AuthService.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtProvider.java
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 🔥 BE

#240 [BE] hotfix: Swagger에 접근이 되지 않는 문제 해결
  backend/src/main/java/capstone/backend/domain/pomodoro/exception/PomodoroDurationException.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtAuthenticationFilter.java
Labels: 🐞 BugFix, 🔥 BE

#247 아이젠하워 추가 API 연동
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/endpoints.ts
  frontend/src/components/eisenhower/TaskModal.tsx
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/eisenhower/view/PriorityView.tsx
  frontend/src/components/today/TodayMainDashborad.tsx
  frontend/src/components/ui/Modal/EisenhowerAi.tsx
  frontend/src/hooks/queries/eisenhower/useEisenhowerAiRecommendation.ts
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/services/eisenhowerService.ts
  frontend/src/services/todayService.ts
Labels: ✨ Feature, 📬 API, 🌈 FE

#248 [FE]: 브레인스토밍 <-> 보관함 <-> 오늘의 할 일 관련 작업 처리
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/endpoints.ts
  frontend/src/components/inventory/InventoryItemCard.tsx
  frontend/src/components/today/ReminderList.tsx
  frontend/src/components/today/TodayList.tsx
  frontend/src/components/today/TodayMainDashborad.tsx
  frontend/src/components/ui/brainstorming/MoveToInventoryModal.tsx
  frontend/src/components/ui/chart/DailyCompletionChart.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/components/ui/switch.tsx
  frontend/src/hooks/queries/analysis/useGetTodayTaskAnalysis.ts
  frontend/src/hooks/queries/inventory/folder/useUpdateFolderName.ts
  frontend/src/hooks/queries/inventory/item/useCreateInventoryItem.ts
  frontend/src/hooks/queries/inventory/item/useGetRecentInventory.ts
  frontend/src/hooks/queries/today/useDeleteTodayTodo.ts
  frontend/src/hooks/queries/today/useUpdateStatusTodo.ts
  frontend/src/pages/brainstorming.tsx
  frontend/src/pages/inventory.tsx
  frontend/src/pages/inventoryDetail.tsx
  frontend/src/pages/today.tsx
  frontend/src/services/analysisService.ts
  frontend/src/services/inventoryFolderService.ts
  frontend/src/services/inventoryItemService.ts
  frontend/src/services/todayService.ts
  frontend/src/types/analysis.ts
  frontend/src/types/api/analysis/index.ts
  frontend/src/types/api/analysis/request.ts
  frontend/src/types/api/analysis/response.ts
  frontend/src/types/api/inventory/item/request.ts
  frontend/src/types/api/inventory/item/response.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API, 🌈 FE

#252 뽀모도로 분석 API 연동
  frontend/src/api/endpoints.ts
  frontend/src/components/today/TodayMainDashborad.tsx
  frontend/src/components/ui/chart/PomodoroCompletionChar.tsx
  frontend/src/hooks/queries/analysis/useGetPomodoroAnalysis.ts
  frontend/src/hooks/queries/analysis/useGetTodayTaskAnalysis.ts
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/services/analysisService.ts
  frontend/src/types/analysis.ts
  frontend/src/types/api/analysis/response.ts
Labels: ✨ Feature, 📬 API, 🌈 FE

#254 [FE]: 브레인스토밍 -> 보관함 API 수정
  frontend/src/api/endpoints.ts
  frontend/src/components/ui/brainstorming/MoveToInventoryModal.tsx
  frontend/src/hooks/queries/inventory/item/useCreateInventoryItem.ts
  frontend/src/services/inventoryItemService.ts
Labels: ✨ Feature, 📬 API, 🌈 FE

#258 로그인 페이지 퍼블리싱 및 QA
  frontend/src/assets/bubble-character.svg
  frontend/src/hooks/useAuthRedirect.ts
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/pages/callback.tsx
  frontend/src/pages/login.tsx
  frontend/src/pages/matrix.tsx
  frontend/src/pages/today.tsx
Labels: ✨ Feature, 🌈 FE

#263 nodeTaskModal 디자인 수정 및 api 연결
  frontend/src/assets/q1.svg
  frontend/src/assets/q2.svg
  frontend/src/assets/q3.svg
  frontend/src/assets/q4.svg
  frontend/src/components/ui/Dialog.tsx
  frontend/src/components/ui/Modal/NodeTaskModal.tsx
  frontend/src/components/ui/Tabs.tsx
  frontend/src/hooks/queries/brainstorming/useCreateMatrix.ts
  frontend/src/pages/brainstorming.tsx
  frontend/src/services/brainstormingService.ts
  frontend/src/types/api/brainstorming/request.ts
Labels: ✨ Feature, 🎨 Html&css, 🌈 FE

#269 [FE] qa: 오늘의 할 일 수정
  frontend/src/assets/check-fill.svg
  frontend/src/assets/check.svg
  frontend/src/assets/plus.svg
  frontend/src/components/today/PomodoroCard.tsx
  frontend/src/components/today/ReminderList.tsx
  frontend/src/components/today/TodayList.tsx
  frontend/src/components/today/TodayMainDashborad.tsx
  frontend/src/components/ui/chart/DailyCompletionChart.tsx
  frontend/src/components/ui/chart/PomodoroCompletionChar.tsx
  frontend/src/components/ui/chart/TodayCompleteChart.tsx
  frontend/src/components/ui/header/Header.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/pages/today.tsx
Labels: 🔨 Refactor, 🌈 FE

#250 [BE] hotfix: 보관함 아이템 생성 중복 API 제거
  backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryItemController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
Labels: 📬 API, 🔨 Refactor, 🔥 BE

#267 [BE] hotfix: 기본 폴더 확인용 boolean 값 추가
  backend/src/main/java/capstone/backend/domain/bubble/controller/v2/BubbleController.java
  backend/src/main/java/capstone/backend/domain/bubble/service/BubbleService.java
  backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryFolderController.java
  backend/src/main/java/capstone/backend/domain/inventory/controller/InventoryItemController.java
  backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryFolderRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryItemCreateRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryItemMoveRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryItemUpdateRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/dto/response/InventoryFolderResponse.java
  backend/src/main/java/capstone/backend/domain/inventory/dto/response/InventoryItemResponse.java
  backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryFolder.java
  backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryItem.java
  backend/src/main/java/capstone/backend/domain/inventory/repository/InventoryItemRepository.java
  backend/src/main/java/capstone/backend/domain/inventory/service/InventoryFolderService.java
  backend/src/main/java/capstone/backend/domain/inventory/service/InventoryItemService.java
Labels: 📬 API, 🚨 HotFix, 🔥 BE

#274 [FE] qa: 마인드맵 수정사항 반영
  frontend/src/components/mindmap/CustomNode.tsx
  frontend/src/components/mindmap/MindmapSkeleton.tsx
  frontend/src/components/mindmap/MindmapWrapper.tsx
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/pages/mindmap.tsx
  frontend/src/store/mindMapStore.ts
  frontend/src/styles/index.css
Labels: 🔨 Refactor, 🌈 FE

#276 [hotfix]: 사이드바 활성화 로직 수정
  frontend/src/components/ui/sidebar/Sidebar.tsx
Labels: 🐞 BugFix, 🌈 FE

#282 [FE] qa: 보관함 수정사항 반영
  frontend/src/components/inventory/InventoryItemCard.tsx
  frontend/src/components/inventory/modal/CreateFolderMoal.tsx
  frontend/src/components/ui/header/Header.tsx
  frontend/src/pages/inventory.tsx
  frontend/src/pages/inventoryDetail.tsx
  frontend/src/types/inventory.ts
Labels: 🔨 Refactor, 🌈 FE

#288 리프레시 토큰 등 로그인 로직 관련 수정
  frontend/src/api/client.ts
  frontend/src/api/endpoints.ts
  frontend/src/assets/sad-bubble.svg
  frontend/src/components/eisenhower/FilterBar.tsx
  frontend/src/components/eisenhower/TaskModal.tsx
  frontend/src/components/ui/Modal/NodeTaskModal.tsx
  frontend/src/components/ui/Modal/WithdrawalModal.tsx
  frontend/src/components/ui/header/Header.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/hooks/use-mobile.ts
  frontend/src/hooks/useAuthRedirect.ts
  frontend/src/hooks/useWithdrawAuth.ts
  frontend/src/pages/NotFound.tsx
  frontend/src/pages/matrix.tsx
  frontend/src/routes.ts
  frontend/src/services/authService.ts
  frontend/src/store/authStore.ts
  frontend/src/utils/cookie.ts
Labels: 🌈 FE

#285 [BE] hotfix: 보관함 수정사항
  backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryItemCreateRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/dto/request/InventoryItemUpdateRequest.java
  backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryFolder.java
  backend/src/main/java/capstone/backend/domain/inventory/entity/InventoryItem.java
  backend/src/main/java/capstone/backend/domain/inventory/repository/InventoryFolderRepository.java
  backend/src/main/java/capstone/backend/domain/inventory/repository/InventoryItemRepository.java
  backend/src/main/java/capstone/backend/domain/inventory/service/InventoryFolderService.java
  backend/src/main/java/capstone/backend/domain/inventory/service/InventoryItemService.java
Labels: 📬 API, 🚨 HotFix, 🔥 BE

#295 [BE] fix: 뽀모도로 타이머 기록 타입 수정
  backend/src/main/java/capstone/backend/domain/pomodoro/controller/v2/DailyPomodoroSummaryController.java
  backend/src/main/java/capstone/backend/domain/pomodoro/dto/response/DailyPomodoroDTO.java
  backend/src/main/java/capstone/backend/domain/pomodoro/schema/DailyPomodoroSummary.java
  backend/src/main/java/capstone/backend/domain/pomodoro/schema/PomodoroCycle.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/DailyPomodoroSummaryService.java
  backend/src/main/java/capstone/backend/domain/pomodoro/service/PomodoroService.java
  backend/src/main/java/capstone/backend/domain/pomodoro/util/PomodoroTimeUtils.java
Labels: 📬 API, 🔨 Refactor, 🔥 BE

#294 [FE] qa 추가 수정 사항
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/mindmap/MindmapWrapper.tsx
  frontend/src/components/today/TodayList.tsx
  frontend/src/components/today/TodayMainDashborad.tsx
  frontend/src/components/ui/chart/PomodoroCompletionChar.tsx
  frontend/src/components/ui/chart/PomodoroCompletionChart.tsx
  frontend/src/hooks/queries/category/useGetCategoryList.ts
  frontend/src/hooks/queries/today/useCreateTodayTask.ts
  frontend/src/pages/mindmap.tsx
  frontend/src/store/mindMapStore.ts
  frontend/src/types/analysis.ts
Labels: 🔨 Refactor, 🌈 FE

#307 [FE] qa 반영
  frontend/src/components/today/TodayList.tsx
  frontend/src/components/ui/chart/DailyCompletionChart.tsx
  frontend/src/components/ui/chart/PomodoroCompletionChart.tsx
  frontend/src/components/ui/chart/TodayCompleteChart.tsx
Labels: 🔨 Refactor, 🌈 FE

#311 카테고리 기능 관련 QA
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/ui/Modal/NodeTaskModal.tsx
  frontend/src/pages/matrix.tsx
  frontend/src/types/api/brainstorming/request.ts
Labels: 🐞 BugFix, 🌈 FE

#318 [FE] QA 추가 반영
  frontend/src/components/today/ReminderList.tsx
  frontend/src/components/today/TodayList.tsx
  frontend/src/layouts/DefaultLayout.tsx
  frontend/src/styles/index.css
Labels: 🚨 HotFix, 🌈 FE

#327 [FE] qa: 하단바 active 버그 수정
  frontend/src/components/eisenhower/TaskModal.tsx
  frontend/src/components/eisenhower/view/CompletedView.tsx
  frontend/src/components/eisenhower/view/PriorityView.tsx
  frontend/src/components/ui/Modal/WithdrawalModal.tsx
  frontend/src/components/ui/chart/DailyCompletionChart.tsx
  frontend/src/components/ui/sidebar/BottomBar.tsx
  frontend/src/hooks/useAuthRedirect.ts
  frontend/src/hooks/useDebounceMindmapUpdate.ts
  frontend/src/pages/brainstorming.tsx
  frontend/src/pages/mindmap.tsx
  frontend/src/pages/pomodoro.tsx
  frontend/src/services/authService.ts
  frontend/src/store/pomodoro.ts
Labels: 🚨 HotFix, 🌈 FE

#329 [FE] feat: 알림 기능 구현
  frontend/src/api/endpoints.ts
  frontend/src/components/ui/Modal/WithdrawalModal.tsx
  frontend/src/components/ui/header/Header.tsx
  frontend/src/components/ui/header/NotificationCard.tsx
  frontend/src/components/ui/sidebar/Sidebar.tsx
  frontend/src/hooks/queries/eisenhower/useGetNotification.ts
  frontend/src/hooks/useWithdrawAuth.ts
  frontend/src/services/eisenhowerService.ts
  frontend/src/types/api/eisenhower/response.ts
  frontend/src/types/task.ts
Labels: ✨ Feature, 🐞 BugFix, 📬 API, 🌈 FE

#341 AI 사분면 추천 오류 및 드래그앤드롭 오류 해결
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/ui/Modal/EisenhowerAi.tsx
  frontend/src/hooks/queries/eisenhower/useEisenhowerAiRecommendation.ts
Labels: 🚨 HotFix, 🌈 FE

#332 [BE] refactor: 프롬프트 최적화
  gpt/prompts/brainstorming/chunk_analysis_prompt.txt
  gpt/prompts/brainstorming/chunk_analysis_system_prompt.txt
  gpt/prompts/brainstorming/chunk_analysis_user_prompt.txt
  gpt/prompts/brainstorming/extract_chucks_prompt.txt
  gpt/prompts/brainstorming/extract_chunks_system_prompt.txt
  gpt/prompts/brainstorming/extract_chunks_user_prompt.txt
  gpt/prompts/brainstorming/mindmap_to_chunk_prompt.txt
  gpt/prompts/brainstorming/mindmap_to_chunk_system_prompt.txt
  gpt/prompts/brainstorming/mindmap_to_chunk_user_prompt.txt
  gpt/prompts/eisenhower/eisenhower_order_system_prompt.txt
  gpt/prompts/eisenhower/eisenhower_order_user_prompt.txt
  gpt/routes/brainstorming_router.py
  gpt/routes/eisenhower_router.py
  gpt/utils/prompt_loader.py
Labels: 🔨 Refactor, 🔥 BE

#336 [BE] feat: 오늘의 할 일 분석 저장
  backend/src/main/java/capstone/backend/domain/todayTask/scheduler/TodayTaskAnalysisScheduler.java
Labels: 🔥 BE

#345 [BE] feat: GPT 버블 병합 기능 구현
  gpt/models/brainstorming_request.py
  gpt/models/brainstorming_response.py
  gpt/prompts/brainstorming/merge_chunks_system_prompt.txt
  gpt/prompts/brainstorming/merge_chunks_user_prompt.txt
  gpt/routes/brainstorming_router.py
  gpt/routes/eisenhower_router.py
Labels: ✨ Feature, 📬 API, 🔥 BE

#347 아이젠하워 버그 수정
  frontend/src/components/eisenhower/card/TaskCard.tsx
  frontend/src/components/eisenhower/view/PriorityView.tsx
  frontend/src/components/ui/Modal/EisenhowerAi.tsx
  frontend/src/hooks/queries/eisenhower/useEisenhowerAiRecommendation.ts
  frontend/src/hooks/useTaskDnD.ts
  frontend/src/pages/login.tsx
  frontend/src/pages/matrix.tsx
  frontend/src/styles/index.css
Labels: 🐞 BugFix, 🌈 FE

#355 프론트 추가 QA
  frontend/src/components/eisenhower/filter/DateRangePicker.tsx
  frontend/src/components/inventory/InventoryItemCard.tsx
  frontend/src/components/ui/Modal/EisenhowerAi.tsx
  frontend/src/components/ui/Modal/NodeTaskModal.tsx
  frontend/src/pages/brainstorming.tsx
Labels: 🐞 BugFix, 🌈 FE

#360 [BE] feat: 버블 병합 API 구현
  backend/src/main/java/capstone/backend/domain/bubble/controller/v2/BubbleController.java
  backend/src/main/java/capstone/backend/domain/bubble/dto/request/MergeBubbleRequest.java
  backend/src/main/java/capstone/backend/domain/bubble/repository/BubbleRepository.java
  backend/src/main/java/capstone/backend/domain/bubble/service/BubbleService.java
Labels: 📬 API, 🔥 BE

#348 [BE] refactor: 아이젠하워 알림 기능 dueDate가 하루 남은 일정 반환으로 수정
  backend/src/main/java/capstone/backend/domain/eisenhower/service/EisenhowerNotificationService.java
Labels: 📬 API, 🔨 Refactor, 🔥 BE

#352 [BE] feat: 최초 로그인 / 재로그인 분기 처리
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/domain/auth/dto/response/AccessTokenResponse.java
  backend/src/main/java/capstone/backend/domain/auth/dto/response/TokenResponse.java
  backend/src/main/java/capstone/backend/domain/auth/service/AuthService.java
  backend/src/main/java/capstone/backend/domain/member/controller/MemberController.java
  backend/src/main/java/capstone/backend/domain/member/scheme/Member.java
  backend/src/main/java/capstone/backend/domain/member/service/MemberService.java
  backend/src/main/java/capstone/backend/global/security/oauth2/service/CustomOAuth2UserService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#362 [FE] feat: 튜토리얼 기능 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/endpoints.ts
  frontend/src/assets/onboarding/onboarding-mobile-1.png
  frontend/src/assets/onboarding/onboarding-mobile-3.png
  frontend/src/assets/onboarding/onboarding-mobile-4.png
  frontend/src/assets/onboarding/onboarding-mobile-5.png
  frontend/src/assets/onboarding/onboarding-pc-1.png
  frontend/src/assets/onboarding/onboarding-pc-2.png
  frontend/src/assets/onboarding/onboarding-pc-3.png
  frontend/src/assets/onboarding/onboarding-pc-4.png
  frontend/src/assets/onboarding/onboarding-pc-5.png
  frontend/src/components/ onboarding/OnboardingSlide.tsx
  frontend/src/hooks/queries/auth/usePatchRegister.ts
  frontend/src/hooks/useAuthRedirect.ts
  frontend/src/pages/callback.tsx
  frontend/src/pages/onboarding.tsx
  frontend/src/routes.ts
  frontend/src/services/authService.ts
Labels: ✨ Feature, 🌈 FE

#365 [FE] fix: 모바일 화면 디자인 수정
  frontend/src/components/ onboarding/OnboardingSlide.tsx
  frontend/src/components/mindmap/MindmapWrapper.tsx
  frontend/src/hooks/useAuthRedirect.ts
  frontend/src/pages/mindmap.tsx
  frontend/src/pages/onboarding.tsx
Labels: ✨ Feature, 🎨 Html&css

#369 [fix]: 튜토리얼 페이지 리다이렉트 문제 수정
  frontend/src/pages/callback.tsx
  frontend/src/routes.ts
  frontend/src/services/authService.ts
Labels: 🚨 HotFix, 🌈 FE
