Repository kookmin-sw/capstone-2025-25, pull requests merged in 2025-03, with the labels that each got.

#19 GPT API 리팩토링 및 Request/Response 구조 수정
  gpt/models/request.py
  gpt/routes/gpt.py
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 🔥 BE

#21 GPT Server Docker 배포 및 GitHub Actions CI/CD 구축
  .github/workflows/gpt-ci-cd.yml
  gpt/Dockerfile
  gpt/docker-compose.yml
Labels: ⚙ Chore, 🌏 Deploy, 🔥 BE

#26 Feat/13 login
  .gitignore
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/domain/auth/dto/request/RefreshAccessTokenRequest.java
  backend/src/main/java/capstone/backend/domain/auth/dto/response/RefreshAccessTokenResponse.java
  backend/src/main/java/capstone/backend/domain/auth/exception/AccessTokenExpiredException.java
  backend/src/main/java/capstone/backend/domain/auth/exception/RefreshTokenExpiredException.java
  backend/src/main/java/capstone/backend/domain/auth/exception/TokenNotFoundException.java
  backend/src/main/java/capstone/backend/domain/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/capstone/backend/domain/auth/scheme/RefreshToken.java
  backend/src/main/java/capstone/backend/domain/auth/service/AuthService.java
  backend/src/main/java/capstone/backend/domain/member/exception/MemberNotFoundException.java
  backend/src/main/java/capstone/backend/domain/member/repository/MemberRepository.java
  backend/src/main/java/capstone/backend/domain/member/scheme/Member.java
  backend/src/main/java/capstone/backend/domain/member/scheme/Role.java
  backend/src/main/java/capstone/backend/global/log/LoggerFilter.java
  backend/src/main/java/capstone/backend/global/security/SecurityConfig.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtProvider.java
  backend/src/main/java/capstone/backend/global/security/oauth2/exception/OAuth2AuthenticationProcessingException.java
  backend/src/main/java/capstone/backend/global/security/oauth2/handler/OAuth2AuthenticationFailureHandler.java
  backend/src/main/java/capstone/backend/global/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/capstone/backend/global/security/oauth2/service/CustomOAuth2UserService.java
  backend/src/main/java/capstone/backend/global/security/oauth2/service/OAuth2UserService.java
  backend/src/main/java/capstone/backend/global/security/oauth2/user/CustomOAuth2User.java
  backend/src/main/java/capstone/backend/global/security/oauth2/user/OAuth2Provider.java
  backend/src/main/java/capstone/backend/global/security/oauth2/user/OAuth2UserInfo.java
  backend/src/main/java/capstone/backend/global/security/oauth2/user/OAuth2UserInfoFactory.java
  backend/src/main/java/capstone/backend/global/security/oauth2/user/info/GoogleOAuth2UserInfo.java
  backend/src/main/java/capstone/backend/global/security/oauth2/user/info/KakaoOAuth2UserInfo.java
  backend/src/main/java/capstone/backend/global/security/oauth2/user/info/NaverOAuth2UserInfo.java
Labels: ✨ Feature, 🔥 BE

#33 nvmrc file 추가
  frontend/.nvmrc
Labels: ⚙ Chore

#27 Chore/4 project setting
  .github/workflows/backend-ci-cd.yml
  backend/docker-compose.yml
Labels: ⚙ Chore, ✨ Feature, 🌏 Deploy, 🔥 BE

#36 GPT Server 코드 리팩터링 및 구조 변경
  gpt/config.py
  gpt/main.py
  gpt/routes/gpt.py
  gpt/utils/__init__.py
  gpt/utils/logging.py
  gpt/utils/mindmap.py
Labels: ✨ Feature, 🌏 Deploy, 🐞 BugFix, 📬 API, 🔨 Refactor, 🔥 BE

#37 TanStack Query 라이브러리 설치 및 API 호출 구조 모듈화 #28
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/client.ts
  frontend/src/api/endpoints.ts
  frontend/src/hooks/.gitkeep
  frontend/src/hooks/queries/useMindmap.ts
  frontend/src/root.tsx
  frontend/src/services/mindmapService.ts
  frontend/src/types/api/mindmap/index.ts
  frontend/src/types/api/mindmap/request.ts
  frontend/src/types/api/mindmap/response.ts
Labels: ⚙ Chore, ✨ Feature, 🌈 FE

#40 Refactor/39 refactoring
  .github/workflows/backend-ci-cd.yml
  .github/workflows/gpt-ci-cd.yml
  backend/docker-compose.yml
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/domain/auth/dto/request/RefreshAccessTokenRequest.java
  backend/src/main/java/capstone/backend/domain/auth/exception/TokenNotFoundException.java
  backend/src/main/java/capstone/backend/domain/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/capstone/backend/domain/auth/scheme/RefreshToken.java
  backend/src/main/java/capstone/backend/domain/auth/service/AuthService.java
  backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/request/MindMapRequest.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapResponse.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/Edge.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/MindMap.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/MindMapType.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/Node.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/NodeData.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/NodeType.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/Position.java
  backend/src/main/java/capstone/backend/domain/mindmap/exception/MindMapNotFoundException.java
  backend/src/main/java/capstone/backend/domain/mindmap/repository/MindMapRepository.java
  backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
  backend/src/main/java/capstone/backend/global/property/JwtProperty.java
  backend/src/main/java/capstone/backend/global/property/RedisProperty.java
  backend/src/main/java/capstone/backend/global/redis/RedisConfig.java
  backend/src/main/java/capstone/backend/global/redis/RedisService.java
  backend/src/main/java/capstone/backend/global/redis/batch/MindMapPublisher.java
  backend/src/main/java/capstone/backend/global/redis/batch/MindMapSubscriber.java
  backend/src/main/java/capstone/backend/global/redis/batch/RedisPubSubConfig.java
  backend/src/main/java/capstone/backend/global/redis/cache/MindMapCacheService.java
  backend/src/main/java/capstone/backend/global/redis/cache/RedisCacheConfig.java
  backend/src/main/java/capstone/backend/global/security/SecurityConfig.java
  backend/src/main/java/capstone/backend/global/security/jwt/JwtProvider.java
  backend/src/main/java/capstone/backend/global/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/capstone/backend/mindmap/controller/MindMapController.java
Labels: ⚙ Chore, 🔨 Refactor, 🔥 BE

#42 fix: docker-compose.yml 문법 오류 수정 & ci-cd.yml 에서 환경 변수 적용
  .github/workflows/backend-ci-cd.yml
  backend/docker-compose.yml
Labels: 🌏 Deploy, 🐞 BugFix, 🔥 BE

#43 fix: Docker Image를 latest 버전으로 변경
  .github/workflows/backend-ci-cd.yml
  backend/docker-compose.yml
Labels: ⚙ Chore, 🌏 Deploy, 🐞 BugFix, 🚨 HotFix, 🔥 BE

#47 Chore/4 project setting
  backend/src/main/java/capstone/backend/domain/auth/controller/AuthController.java
  backend/src/main/java/capstone/backend/global/property/RedisProperty.java
  backend/src/main/java/capstone/backend/global/redis/RedisConfig.java
  backend/src/main/java/capstone/backend/global/security/oauth2/handler/OAuth2AuthenticationFailureHandler.java
Labels: ⚙ Chore, 🌏 Deploy, 🔥 BE

#48 Feat/45 mindmap
  backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/request/MindMapRequest.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/request/UpdateMindMapOrderRequest.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapResponse.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/MindMap.java
  backend/src/main/java/capstone/backend/domain/mindmap/exception/InvalidMindMapDateException.java
  backend/src/main/java/capstone/backend/domain/mindmap/exception/MindMapNotFoundException.java
  backend/src/main/java/capstone/backend/domain/mindmap/repository/MindMapRepository.java
  backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#56 chore: ci-cd 환경변수 설정 기능 추가
  .github/workflows/backend-ci-cd.yml
Labels: ⚙ Chore, 🌏 Deploy, 🔥 BE

#57 feat: memory leak 방지를 위한 redisConnectionFactory 제거 로직 추가
  backend/src/main/java/capstone/backend/global/redis/RedisConfig.java
Labels: ⚙ Chore, 🔥 BE

#58 fix: docker-compose.yml에 들어가는 환경변수 제거
  .github/workflows/backend-ci-cd.yml
  backend/docker-compose.yml
Labels: ⚙ Chore, 🌏 Deploy, 🔥 BE

#52 마인드맵 구현
  backend/src/main/java/capstone/backend/domain/mindmap/controller/MindMapController.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/request/MindMapRequest.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/request/UpdateMindMapTitleRequest.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapGroupListResponse.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapListResponse.java
  backend/src/main/java/capstone/backend/domain/mindmap/dto/response/MindMapResponse.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/Measured.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/MindMap.java
  backend/src/main/java/capstone/backend/domain/mindmap/entity/Node.java
  backend/src/main/java/capstone/backend/domain/mindmap/exception/InvalidMindMapDateException.java
  backend/src/main/java/capstone/backend/domain/mindmap/exception/MindMapNotFoundException.java
  backend/src/main/java/capstone/backend/domain/mindmap/exception/NodeNotFoundException.java
  backend/src/main/java/capstone/backend/domain/mindmap/repository/MindMapRepository.java
  backend/src/main/java/capstone/backend/domain/mindmap/service/MindMapService.java
Labels: ✨ Feature, 📬 API, 🔥 BE

#54 GPT API 리팩터링
  gpt/main.py
  gpt/models/request.py
  gpt/routes/gpt.py
Labels: ✨ Feature, 📬 API, 🔨 Refactor, 🔥 BE
